### ISSUE TITLE
Rubber band does not XOR properly

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#12]
SHEP: Rubber band mode does XOR itself after each draw operation. Stepping through in the debugger makes it clear that it attempts to XOR itself, but seems to be missing somehow. As a result, we get lines that look like this:

![screenshot 2015-08-25 08 32 47 copy](https://cloud.githubusercontent.com/assets/378677/9471197/14a383fc-4b04-11e5-894b-cdd59464b36b.jpg)

**Comment by philburk** [comment]
The dragging of the selection region works great. And the moving cursor works. Those use XOR mode. But the Rubber band mode does not work, which is odd. There seems to be a slight mismatch between draw and undraw that leaves some gray pixels. Maybe it is caused by anti-aliasing! The other XOR drawing modes are vertical or horizontal. If I drag the Rubber band line around in a circle repeatedly it leave grey smudges except for the vertical and horizontal directions! Maybe the diagonal draw is anti-aliased.

**Comment by andrewcsmith** [comment]
That works! And it even helps recapture that 80s flavor...

![shep-antialiased](https://cloud.githubusercontent.com/assets/378677/9471400/f8338586-4b04-11e5-9fc0-b89823e39fcb.jpg)

**Comment by philburk** [comment]
Ah yes. I remember when pixels were visible to the naked eye.

Cool. Let's keep the aliasing for awhile. It is more authentic.
