### ISSUE TITLE
Text too small and too high

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#14]
The text in SHEP should more closely match this photo from the manual. It was a screenshot from a Mac.

![shep-from-manual](https://cloud.githubusercontent.com/assets/5175913/9471659/38529a02-4b06-11e5-9f97-de3f8949213f.jpg)

**Comment by andrewcsmith** [comment]
I just moved the text down 3 pixels. It does look to me like the forth code is drawing the string 3 pixels down from the top-left of the bounding box. 

```
graphics.fth:366

: CG.DRAW.TITLE ( -- , Draw title by control )
        get.title: self   ?dup
        IF
                iv-cg-text-size gr.height! \ 1 gr.color!
                iv-cg-text-font gr.font!
                iv-cg-leftx iv-cg-topy  3 -
                rot gr.xytext
     THEN
;
```

Also, I believe that the smaller text (Paste, Pans, Custom) actually means "disabled"—look at how in the Windows implementation it's just red text, rather than smaller text.

![screenshot 2015-08-27 09 20 36](https://cloud.githubusercontent.com/assets/378677/9526256/1ad758f8-4c9d-11e5-9fdf-d0cdcd8e66eb.png)

![screenshot 2015-08-27 09 31 05](https://cloud.githubusercontent.com/assets/378677/9526515/8fd5fa6e-4c9e-11e5-8861-f34c37bd7328.png)
