### ISSUE TITLE
pforth include requires full path

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#19]
Look into this—`include pieces/splorp.fth` should work, assuming that HMSL was originally run from the target directory.

**Comment by andrewcsmith** [comment]
Commit 22773f41be92e76d02eb8bd90365786df40c2419 should fix this. The command line executable now runs in a working directory which includes the pieces, so you should just be able to run the pieces with `include pieces/splorp.fth`.

**Comment by philburk** [comment]
OK, I can include files in the pieces folder, eg. "pieces/splorp.fth".
But I cannot include file in the fth or tools folder!

include pieces/splorp.fth 
Include pieces/splorp.fth
Enter:  SPLORP
    include added 8388 bytes,122700 left.
   ok
Stack<10> 

include tools/score_entry.fth 
Include tools/score_entry.fth
Could not find file tools/score_entry.fth
Stack<10> 
THROW code = -1 
ABORT
    ok
Stack<10> 
include /Users/phil/Work/HMSL/hmsl/tools/score_entry.fth  
Include /Users/phil/Work/HMSL/hmsl/tools/score_entry.fth
(LOCAL) - Note: INDEX redefined as a local variable in NS.ADD.SHAPE
HEX redefined.
Warning - Potential conflict between note names and
hexadecimal numbers. Use $ for hex numbers: $ C3
G redefined.
    include added -11472 bytes,131088 left.

**Comment by philburk** [comment]
The warnings about score_entry.fth  conflicts are expected.

**Comment by philburk** [comment]
I have renamed all occurrences of pieces/splorp.fth that I can find to prevent loading. But I can still include "pieces/splorp.fth"!!  Where is it finding this file?

Oh!  It is inside the hmsl.app package!  This is not a fix. It needs to load files from outside the package so that the user can modify the files.

**Comment by andrewcsmith** [comment]
There are two targets that the xcode project can build. 

1. A command-line program, which functions exactly like the old HMSL in that you run it from the command line and it cares about its own directory structure.
2. An hmsl.app package which, in addition to building target 1, adds a shell script that opens the command line program in a new Terminal window, sets up the directory structure required for OSX to assign the program a dock icon, and copies selected files (pforth.dic, pieces/*) to the runtime directory of `hmsl` (by default, `hmsl.app/Contents/Resources`) to make for easier loading.

You can load files from outside the package with a path relative to the `hmsl.app/Contents/Resources` directory. `../../../../../../../../hmsl/tools/score_entry.fth` loads `score_entry.fth` on my system. Or you can provide an absolute path, of course. The build process copies the `pieces/` folder to the running directory of `hmsl.app/Contents/Resources`, so there's no reason it couldn't copy over the `hmsl/` and `tools/` directories as well.

Instead of double-clicking on hmsl.app you could open a new Terminal window and run `hmsl.app/Contents/MacOS/hmsl`. Assuming you have `pforth.dic` in the same location as `hmsl.app`, that will work fine.

**Comment by philburk** [comment]
Thanks. I understand now. So it seems we have a few options:

1) Provide a self-contained hmsl.app that contains pforth.dic and all the source code files that can be easily loaded using relative paths. This would be good for exploring HMSL but not good for writing pieces. It also makes it hard for people to save a modified binary dictionary.

2) Provide the hmsl shell command that we can place in the HMSL folder. Then folks can load relative folders, and put their own code in that folder. But folks should probably not put their own code in the HMSL folder because it may get overwritten when we release code.  Also we don't get the app in the doc and the graphics window gets lost.

3) Provide a self contained hmsl.app with just a pforth.dic that changes directory to ../../../ so that it ends up in the same folder as the hmsl.app file. Would that be hard?

I think that we will probably want to provide a CD, $CD, PWD, LS and $LS commands to make life easier. This is starting to get into the area of an enhancement but it is basic functionality that is part of the Forth, not HMSL itself. So it seems OK. We'll see if there is time.

**Comment by andrewcsmith** [comment]
Okay, I think that option 1 would be the best—here's why: we can include the full package for anyone who wants to just run `include pieces/splorp.fth` and get the piece to work, but a power user can just start up hmsl from *any* directory containing pforth.dic and that will be the working directory for any commands. This is because hmsl uses the pforth.dic file relative to the launch directory, not relative to the actual hmsl executable.

**Comment by philburk** [comment]
OK, let's go with option 1 for now. I will use the shell version because I need to port some of the old files in tools/ and screens/. Then we can add them to the package.

**Comment by philburk** [comment]
I modified the startup shell script so that HMSL runs from the same directory as the hmsl.app. So now we can include "pieces/splorp.fth".
