### ISSUE TITLE
add ASSIGN command

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#32]
The original HMSL supported an ASSIGN word that let the developer map a virtual device such as "HT:" to a specific directory. Then the user could 
      INCLUDE ht:somefile.fth

The old code is in H4thSystem/file_tools.f

**Comment by rsnewcomb** [comment]
May I assume that the 'include' and '$include' commands are still valid, and that until ASSIGN works, I should use these to hard code file paths?  I made heavy use of ASSIGN since in HMSL/H4th, I rebuilt the HMSL app on each run with a series of 'include' and '$Include' statements, like so: 

assign  hmsl:			ocat:appls:languages:hmsl_v4.05  --  (where the HMSL source lived)
assign  hmsl_source:	hmsl:
assign  hmsl_user:	        hmsl:
assign  h:    			hmsl_source:source
assign  ho:   			hmsl_source:ode
assign  hh:  			hmsl_source:hostdep
assign  hsys: 			hmsl_source:H4thSystem
assign  hp:   			hmsl_user:pieces
assign  ht:   			hmsl_user:tools
assign  hsc:  			hmsl_user:screens
assign  hmf:  			hmsl_user:MIDIFiles
assign  hx:   			hmsl_user:tests
assign  hwork:		        hmsl_user:work
assign  ram: 		        hmf:
assign  h4th: 			hmsl_source:H4th
assign  metrics:		hmsl_source:metrics
assign  mita:			ocat:data:arm:r&d:mita_src_v0.80[01.04.07]  -- (where my source lived) 
assign  x_data:		ocat:data:x_data -- (where my raw input table/array data lived and where log files where written to)
assigns?
include ht:midifile
include hsys:debugger
include hsys:floatingpoint
fpinit
include hsys:logto

**Comment by philburk** [comment]
INCLUDE and INCLUDE? should work the same as before.

If you run from the hmsl folder then you can substitute the relarive path for the assign. Also add ".fth" suffix, eg.

Change:    include hp:splorp
To:  include  pieces/splorp.fth

You can put your folder next to hmsl, eg. "rsn" and use:
   include ../rsn/whatever/somefile.fth
or use absolute paths.

**Comment by rsnewcomb** [comment]
I have begun testing my HMSL 4.05-4.21 code from the 'top', using the compiled binary you provided.  

This command works fine:

anew task-mita_load_prep (works fine)

BUT...

Replacing the ASSIGNS file with a simple word definition with one INCLUDE or $INCLUDE with or without quotes around the relative file path...

: load.prep “../../MITA2/HMSL_OSX/MITA_SRC_v2.0[16.03.02/mita_load_prep.fth” $include ; 
: load.prep include ../../MITA2/HMSL_OSX/MITA_SRC_v2.0[16.03.02/mita_load_prep.fth ;

...I am getting this error:
>
THROW code = -13 
Undefined word!
>

I get the same error for 'debug{'    as well...

Is there a basic cheat sheet on changed syntax that I am lacking?  It has been 15 years since I used this code, so I may just be rusty (I am that, for sure).

**Comment by rsnewcomb** [comment]
An update:  by moving my source files into the same folder as the HMSL app, I am now able to compile classes and methods (200) and global variable/constant declarations (several 100 of them) with problem, lightning fast compared to old 68000 land :-)  So, if you can correct my Include syntax I think I am on my way!  I will continue testing 'Includes' one source file at a time - complex objects are next...then actual code.  During the day I can now work on this in spare time, but have no USB connected interfaces to push data out or pull it in to/from controller/synths.  Will do that testing at home.  So, some real progress.  Thought you would like to know.

**Comment by philburk** [comment]
I believe you are missing the space after the quote in your filenames. Pass string to $INCLUDE, not INCLUDE.

    " valid string"
    "bogus string"

**Comment by philburk** [comment]
$FOPEN in tools/file_port.fth calls CREATE_FILE and OPEN-FILE in kernel.
INCLUDE calls $INCLUDE calls INCLUDED calls OPEN-FILE

Could add a call to new deferred word MAP.FILENAME in $INCLUDE and $FOPEN.
