### ISSUE TITLE
system build fails with missing file

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#36]
In the README it says to run:
    ./HMSL-OSX -i system.fth

But this fails with:
  PForth V27-LE/32, built Nov  2 2015 09:51:34
  Error in pfLoadDictionary - could not open file
  pfDoForth: Error occured.
  2015-11-02 17:57:51.648 HMSL-OSX[5067:771508] *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

It acts as if the -i option is being ignored and pForth is trying to load pforth.dic.
In hmsl_main.m I see that argc and argv are ignored. This may be related.

**Comment by andrewcsmith** [comment]
Sending you a new build. Let me know if the command line arguments work for your purposes, and give me some samples if they fail.

I didn't include functionality for the space after `-d` yet, because I want to make sure that things are good so far. Once that works I'll rework things to get the space working. (It'll just require a specific NSEnumerator instantiation, rather than an anonymous block.)
