### ISSUE TITLE
Possible bug in windows implementation?

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#6]
This looks to me like a bug—passing in variables to immediately overwrite them. Was this on purpose, or just a result of too much Forth coding?

https://github.com/philburk/hmsl/blob/aa0bc0dea2d73f579ca8f2537b4651ecdf336ff4/native/Win32/pHMSL/src/hmsl_graphics.c#L433-L437

```
void hostGetMouse( uint32 x, uint32 y )
{
	*(int32*)x = gHMSLContext->hg_ev_mouseXY.x;
	*(int32*)y = gHMSLContext->hg_ev_mouseXY.y;
}
```

**Comment by philburk** [comment]
This is really ugly. But intentional. The uint32 x,y are actually pointers!
Should be renamed xptr,yptr. Forth just has a single stack for ints and
pointers. So we just pass the top two values to C and they happen to be
pointers.

Obvious problem when we go to 64 bit pointers unless pforth is on 64bit
mode. Note 64 bit support added after phmsl written.

Feel free to add comments or cleanup windows phmsl as you go. I will review
commits.

BTW, I am on vacation. Using phone for email. Difficult to write much.

Thanks for working on this.

**Comment by andrewcsmith** [comment]
Ah, right. Yes, of course, there are similar pointer sends with strings. That helps. Working on a basic implementation now, so I might have further api questions as we go.
